spring:
  datasource:
    url: jdbc:sqlserver://${DB_HOST};database=${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
    open-in-view: false
  data:
    rest:
      detection-strategy: annotated
  application:
    name: download-manager
server:
  port: ${SERVICE_PORT}
  forward-headers-strategy: framework
